ynput/ayon-traypublisher

server/settings/publish_plugins.py
Replace deprecated flag `-intra` for `-g 1` for FFMPEG encoding.
Matches a similar change in `ayon-core` code here: https://github.com/ynput/ayon-core/pull/758
See:
- https://gist.github.com/tayvano/6e2d456a9897f55025e25035478a3a50#file-gistfile1-txt-L67
- https://www.reddit.com/r/ffmpeg/comments/aeo1la/libx264_intra_option_information_please/
---
This changes default for setting: `ayon+settings://traypublisher/publish/ExtractEditorialPckgConversion/output/ffmpeg_args/output`
Note that this just replaces the default value, if you have settings overrides for this flag you may need to remove your override your updates or update manually.
1. Extracting Editorial Package `editorial_pkg` should still work with the new FFMPEG encoding settings.
=> Settings: Replace deprecated flag `-intra` for `-g 1`

server/settings/imageio.py
Remove deprecated `ocio_config` `ImageIOConfigModel` settings
With [the support of profiles to determine OCIO config in ayon-core](https://github.com/ynput/ayon-core/pull/490) this logic has been superseded and should be removed from each addon still having the deprecated settings.
Related to https://github.com/ynput/ayon-core/issues/785
=> Remove deprecated `ImageIOConfigModel` and `ocio_config` settings

client/ayon_traypublisher/plugins/create/create_editorial.py, client/ayon_traypublisher/plugins/publish/collect_shot_instances.py
When onboarding for the Resolve publisher work, I tried to make the `EditorialSimple` example working from the `traypublisher` but go some issues.
``` text
AttributeError: 'opentimelineio._otio.Timeline' object has no attribute 'each_child'
```
I'm using `opentimelineio-0.16.0` which I believe is defined from 
https://github.com/ynput/ayon-core/blob/874a0f1c4e308ec93828b8eef0487591b8ffd782/client/pyproject.toml#L17
So I think this is an issue which needs to be fixed, please @jakubjezek001 advise on this one :smiley: 
OpentimelineIO PR which remove `each_child`:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1437/files
1. Try to create an `EditorialSimple` from test resources
=> Fix deprecated opentimelineio 'each_child' methods (To Be Discussed).

server/settings/simple_creators.py
The 'vdbcache' product type is used for product types filtering currently for Houdini and Maya based loaders so is a way more sensible default.
I don't know of any loader that would work with the `vdb` product type currently.
1. Publish VDB via tray publisher
2. Should be able to load it into Maya and Houdini
=> Update default product type for the VDB cache simple creator

client/ayon_traypublisher/plugins/create/create_csv_ingest.py
- Extracted file name from basename for processing.
- Improved handling of sequence padding using regex pattern matching.
- Enhanced file filtering based on the extracted file name.
=> Refactor file name handling and sequence padding logic.

client/ayon_traypublisher/plugins/publish/collect_frame_data_from_folder_entity.py, client/ayon_traypublisher/plugins/publish/collect_review_frames.py, client/ayon_traypublisher/plugins/publish/collect_sequence_frame_data.py, client/ayon_traypublisher/plugins/publish/validate_frame_ranges.py
Use task entity attributes instead of folder entity attributes, only if it is set for the instance.
I'm not sure if I've missed any parts where it's also crucial to refactor them in `traypublisher`. This is mostly a bit of 'search' in the code to see where `folder` seems relevant to update.
Not entirely sure how to test these use cases.
1. Test tray publisher sequences and their "assumed" frame ranges.
=> Use task entity attributes instead of folder entity attributes

client/ayon_traypublisher/plugins/create/create_csv_ingest.py, server/settings/creator_plugins.py
These changes resolves #16 
Ensure the Version column in the CSV is optional:
* _When it exists and it's filled up,_ will publish and enforce provided version (**previous behavior**)
* _When it exists but it's empty,_ product will take next available version
* _When it does not exist,_ default logic applies, product will take next available version
Tested via the command line and interactive mode using:
* [AY_240319_0001_ABS - ay_240319_0001_abs_paths_60_empty.csv](https://github.com/user-attachments/files/17298103/AY_240319_0001_ABS.-.ay_240319_0001_abs_paths_60_empty.csv)  column exists but empty
* [AY_240319_0001_ABS - ay_240319_0001_abs_paths_60_mixed.csv](https://github.com/user-attachments/files/17298104/AY_240319_0001_ABS.-.ay_240319_0001_abs_paths_60_mixed.csv)  mix of version …
=> AY-6740 CSV ingest: make Version column optional.

client/ayon_traypublisher/addon.py
resolve #34 
The user should be able to override the user operating the CSV ingest through `AYON_USERNAME` when connection is made through a service account. 
1. Setup connection through a service account
2. Set `AYON_USERNAME` environment variable to an existing user
3. Run the CSV ingest command line
4. Check that the created product are made under the user set through `AYON_USERNAME`
=> CSV ingest allow user override through AYON_USERNAME.

client/ayon_traypublisher/plugins/create/create_csv_ingest.py, server/settings/creator_plugins.py
resolve #24
* Allow CSV ingest to create new shots for non-existent folder paths
* Provide additional server settings for Folder and Task creation
**Current implementation has some limitations**:
* Created shot are pretty much blank as we do not have any OTIO/range/resolution info from the CSV file
This needs to be tested along those changes in `ayon_core`: https://github.com/ynput/ayon-core/pull/1010
1. Create a new package and upload it to your AYON server
2. In CSV settings, enable missing folder creation (`ayon+settings://traypublisher/create/IngestCSV/folder_creation_config`)
3. Prepare a CSV file with Folder Path that do not exist yet
4. Ingest the CSV file through the `publisher` option in traypublisher
5. Ensure data is publish as expected and new blank shot(s) have been created
=> Allow CSV ingest to create new shots.

server/settings/publish_plugins.py
resolve #41 
1. Go to setting `ayon+settings://traypublisher/publish/CollectSequenceFrameData` 
2. Try enabling and disabling different toggles, this should be reflected in the publisher UI.
=> Expose `Collect Original Sequence Frame Data` settings in Addon settings

client/ayon_traypublisher/plugins/create/create_editorial.py
resolve #46 
Everything should work as before
=> Rename `Sequence file` label to `Edit list file` in `Editorial Simple` creator

server/settings/publish_plugins.py
resolve #50 
This PR removes `CollectFrameDataFromAssetEntity` settings completely.  this plugin was previously Optional, but that got later removed https://github.com/ynput/OpenPype/commit/e90d227a234fec278b214c3ed4086350403eda80
1. everything should work as before. 
2. Please report if the missing logic should be implemented instead of removing the redundant settings.
3. Please report if the PR is not backward compatible (copy settings should work fine without implementing conversions)
=> remove redundant settings from `CollectFrameDataFromAssetEntity`

server/settings/publish_plugins.py
resolve #53 
1. when enabled, the conversion should work. 
2. the setting should be backward compatible, copy settings should be fine.
=> Fix default values of `ExtractEditorialPckgConversion`

client/ayon_traypublisher/plugins/create/create_editorial.py, server/settings/editorial_creators.py
Follow up PR to https://github.com/ynput/ayon-traypublisher/pull/44 and https://github.com/ynput/ayon-traypublisher/pull/47
This PR is specifically for enhancing editorial creator settings
- It renames/rearranges some settings and adds description and docstrings.
- it also updates editorial creator attributes
1. Go through settings and validate if the changes enhances the UX of the settings.
2. This PR is backward compatible as it only change the settings' label, copy settings should work fine.
=> Enhance editorial creator settings and creator attributes

client/ayon_traypublisher/plugins/publish/collect_simple_instances.py
Key `outputName` is filled on representation only if is not re-used source representation for review.
The output name affects how published file looks like which should not happen.
There might be other potential solution, and that would be to avoid using source representation and always create new one for review representation, don't know what it would meant.
1. Create package, upload to server and use in bundle.
2. Launch traypublisher.
3. Select project, folder and task.
4. Select `image` create plugin and drop a jpeg to both input and review file inputs.
5. Hit `Publish` and wait.
6. After successful publish look into integrated files, the source file should not end up with `_review.jpg` (which did happen before this PR).
Resolves https://github.com/ynput/ayon-traypublisher/issues/40
=> Avoid setting up output name on source representation

client/ayon_traypublisher/addon.py, client/ayon_traypublisher/api/main.py, client/ayon_traypublisher/api/pipeline.py, client/ayon_traypublisher/csv_publish.py, client/ayon_traypublisher/ui/__init__.py, client/ayon_traypublisher/ui/window.py, server/__init__.py
Tray Publisher now runs in a context of a project that cannot be changed once launched. And adde option to start traypublisher using webactions.
Being able to change project during lifetime of a host process has few problems. But main reason why we changed the behavior is preparation for per project bundle (still will need some changes in future, just preparation).
1. Create package, upload to server, use in bundle. Production or dev bundle, staging does not have option to show webactions.
2. In AYON web UI should be publish action on project, folder and task, that will start traypublisher.
3. When using `Publisher` action in tray, it does ask for project selection before starting traypublisher.
4. Publishing from traypublisher works the same way as before.
Resolves …
=> Chore: Process per project and webactions

client/ayon_traypublisher/csv_publish.py
Use helper methods to fetch entities instead of using ayon api in Ingest CSV.
The helper methods are using cache which might make the logic faster.
1. CSV ingerst still works as before.
=> Ingest CSV: Use create context functions to get entities

client/ayon_traypublisher/plugins/create/create_colorspace_look.py, client/ayon_traypublisher/plugins/publish/collect_colorspace_look.py, client/ayon_traypublisher/plugins/publish/validate_colorspace_look.py
Current `create_colorspace_look` can only published one LUT file at a time.
These changes enable publishing multiple "chained" LUT files to a single product.
To keep current logic, the relevant colorspace look information is now asked per LUT file via dynamic `creator_attributes`.
E.g. for 2 Look Up Table files:
0. Ensure OCIO managed colorspace is enabled from your project (otherwise creator won't appear)
1. From the traypublisher, select `Colorspace Look`
2. Put one or multiple
3. Do not forget to fill up the colorspace additional data in the resulting product instance
4. Ensure publishing go through seemlessly
5. The result should integrate 1 json file with the serialized information + a backup of all of the relevant lut files.
6. (optional) test Nuke load through …
=> AY-7437 Make create_colorspace_look able to handle multiple chained files.

.github/workflows/assign_pr_to_project.yml, client/ayon_traypublisher/plugins/create/create_editorial_advanced.py, client/ayon_traypublisher/plugins/create/create_editorial_simple.py, client/ayon_traypublisher/plugins/publish/collect_clip_instances.py, client/ayon_traypublisher/plugins/publish/collect_editorial_instances.py, package.py, server/settings/editorial_creators.py
This PR introduces a significant improvement to the Editorial workflow by splitting it into two distinct approaches - Simple and Advanced. The Simple workflow maintains the current functionality for basic editorial operations, while the new Advanced workflow provides more sophisticated features for handling complex media folder structures, multiple file types, and enhanced representation capabilities.
The Advanced workflow allows for more flexible content discovery in clip folders, better version handling, and improved control over how different media types are processed and published. This makes it especially useful for studios with complex editorial pipelines involving various media types and folder structures.
- Split editorial creator into Simple and Advanced workflows
- Moved …
=> Editorial Advanced Creator

client/ayon_traypublisher/plugins/publish/collect_simple_instances.py
Flagged on [Discord](https://discord.com/channels/517362899170230292/1339510322733781063/1341772287564714004).
Fixes this issue where attempting to publish multiple representation with similar extension fails:
```
DEBUG: Creating new version ...
DEBUG: Prepared version: v003
DEBUG: http://localhost:5000 "POST /graphql HTTP/1.1" 200 112
DEBUG: Response <RestApiResponse [200]>
DEBUG: Anatomy template name: default
DEBUG: Anatomy template name: default
Traceback (most recent call last):
File "C:\Users\robin\OneDrive\Bureau\dev_ayon\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 158, in process
self.register(instance, file_transactions, filtered_repres)
File "C:\Users\robin\OneDrive\Bureau\dev_ayon\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 256, in …
```
=> Fix publishing multiple representations with common extension (Image).

client/ayon_traypublisher/plugins/publish/collect_simple_instances.py, client/ayon_traypublisher/plugins/publish/validate_frame_ranges.py, server/settings/simple_creators.py
resolve: https://github.com/ynput/ayon-nuke/issues/69
Changes:
* Add SXR image extension support for `plate`, `render` and `image` simple creators.
* Ensure SXR extension is properly validated by `validate_frame_range` plugin
Needs to be tested with: https://github.com/ynput/ayon-core/pull/1165
1. Download this [SXR material](https://drive.google.com/drive/folders/1tl5JVaNIQdWbLfYBgtSHJiYUQ63X4SKy)
2. Publish this material as `image`, `render` or `plate` through the simple creators
3. Gather resulting material in Nuke as `image` and/or `clip`
=> AY-7442 Add SXR support for plate, render and image simple publishers.

server/settings/simple_creators.py
Links to https://github.com/ynput/ayon-speedtree/pull/6
Implemented for external project files to be used in SpeedTree Modeler with AYON plugins
n/a 
1. Build and install the addon
2. Publish
=> Add spm file as publishing format in tray publisher

client/ayon_traypublisher/plugins/create/create_csv_ingest.py, server/settings/creator_plugins.py
resolve: https://github.com/ynput/ayon-traypublisher/issues/62
Add optional column in CSV ingest so that shot width and height can be defined via `Shot Width` and `Shot Height` values in the CSV.
1.Create a new package and upload it to your AYON server
2.Prepare a CSV file with Folder Path that do not exist yet
3. Edit the CSV file with additional  `Shot Width` and `Shot Height` column and values
4.Ingest the CSV file through the publisher option in traypublisher
5.Ensure data is publish as expected and new shot(s) have been created with proper provided resolution
=> AY-7395 Include resolution width and height in CSV ingest.

client/ayon_traypublisher/plugins/publish/collect_shot_instances.py
When reviewing https://github.com/ynput/ayon-core/pull/1255 I realize the provided use-case was not working properly because of missing resolution attribute in `collect_shot_instances`.
1. Run with tests described at https://github.com/ynput/ayon-core/pull/1255
=> Inject resolution attribute in collect_shot_instances.

client/ayon_traypublisher/ui/_projects_widget.py, client/ayon_traypublisher/ui/projects_widget.py, client/ayon_traypublisher/ui/window.py
Use `ProjectsWidget` from ayon-core to display projects.
The change is mostly related to recent changes in https://github.com/ynput/ayon-core/pull/1330 . Up until that PR the `ProjectsWidget` is not available, that's why there is backwards compatible implementation of the widget.
1. The project selection dialog is shown and works with current ayon-core develop.
2. The project selection dialog is shown and works with https://github.com/ynput/ayon-core/pull/1330 and also shows pinned projects.
=> Projects widget: Use ProjectsWidget from ayon-core

server/settings/editorial_creators.py
Refactor `conditionalEnum` -> `conditional_enum`
Avoid logs like:
```
DEBUG settings.settings_field | Deprecated argument: conditionalEnum
```
1. Check whether settings are still ok
=> Settings: Refactor `conditionalEnum` -> `conditional_enum`

client/ayon_traypublisher/csv_publish.py
CSV publish is passing discovered plugins from create context into pyblish utils.
1. CSV publish still does publish.
=> Chore: Use collected plugins in csv publish

client/ayon_traypublisher/plugins/create/create_editorial_simple.py
Use parenting advantage in simple editorial workflow to visualize tree of instances in publisher.
Changes should be backwards compatible. Children instances are automatically removed if parent instance is removed and are automatically disabled if parent instance is disabled.
1. Use ayon-core with https://github.com/ynput/ayon-core/pull/1395 PR.
2. Simple editorial creation should work and should visualize the instances in hierarchy.
3. If a parent is removed then all children are removed too.
4. If a parent is disabled then all children are disabled too.
5. Test if the functionlity works with develop of ayon-core, it should work exactly as before this PR.
=> AY-7790 Simple editorial: Add parenting of instances

client/ayon_traypublisher/plugins/create/create_editorial_advanced.py, client/ayon_traypublisher/plugins/create/create_editorial_simple.py, client/ayon_traypublisher/plugins/publish/collect_editorial_reviewable.py
Unblocking the issue with None type is not possible to add to string type. Also improving consistency of reviewable attribute to be only offered to image based products.
-  Enhances performance and reliability when handling file names with varying characters.
- Removed redundant checks and added a condition to avoid adding `None` values to the prefix.
- Passing instance reviewable attribute for proper reviewable files creation.
1. Use advanced editorial data for testing https://drive.google.com/open?id=18rtOZsSoF2ENNVHxZOv7pBxMBtfLIzYV&usp=drive_fs
2. open publisher from tray and make sure your Advanced editorial creator is enabled `ayon+settings://traypublisher/editorial_creators/editorial_advanced`
3. add following settings from clipboard to the above mentioned category …
=> Fixing few Advanced Editorial bugs

client/ayon_traypublisher/plugins/create/create_csv_ingest.py, client/ayon_traypublisher/plugins/create/create_movie_batch.py, client/ayon_traypublisher/plugins/create/create_online.py
Use kwargs to call product name functions and use cached data to call them if possible.
This is preparation for future change in `get_product_name` functionality and update of already added change in `get_product_name` method.
1. Product names are calculated correctly.
=> Create: Use kwargs to call product name functions
